# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: recontrails-api

frameworkVersion: '3'

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  memorySize: 2048
  stage: production
  runtime: nodejs12.x
  timeout: 15
  region: us-east-2

# The `functions` block defines what code to deploy
functions:
  ReconTrails:
    handler: server.ReconTrails
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http: ANY /{proxy+}
      - http: ANY /

    environment:
      DB_HOST: recon-trails.cjsgvy0zfpqg.us-east-2.rds.amazonaws.com
      DB_HOST_PORT: 3306
      DB_NAME: ReconTrails
      DB_PASS: recontrailsadmin
      DB_USER: admin
      SECRET: bezkoder-secret-key

    # events:
    #   - http:
    #       path: hello-world
    #       method: get
    #       cors: true
